name: build and run tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: mkdir
      run: mkdir build

    - name: cmake build
      run: cmake -DCMAKE_CXX_COMPILER=g++ -Bbuild -H.

    - name: cmake make
      run: cmake --build build/ --target all

    - name: make test
      run: cd build && make test
